# Generated by Django 4.2.20 on 2025-08-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='city',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='country',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='region',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
