# Generated by Django 4.2.20 on 2025-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
